[package]
name = "kuberniva"
version = "0.5.1"
description = "A focused Kubernetes control surface"
authors = ["Vijay Kumar Sevakula"]
license = "MIT"
repository = "https://github.com/velqa/Kuberniva"
homepage = "https://github.com/velqa/Kuberniva"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "kuberniva_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
tauri-plugin-clipboard-manager = "2"
kube = { version = "4.2.0", features = ["client", "config", "rustls-tls", "ws"] }
futures-util = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "process"] }
k8s-openapi = { version = "0.28.0", features = ["v1_32"] }
base64 = "0.22"
x509-parser = "0.18"
chrono = "0.4"
sha2 = "0.10"
shell-words = "1.1"
tauri-plugin-updater = "2.12.0"
tauri-plugin-process = "2.3.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true

[dev-dependencies]
tauri = { version = "2.11.3", features = ["test"] }
